In [6]:
import pandas as pd 
import numpy as np

In [7]:
df = pd.read_csv('data.csv')


df.head()

,Timestamp,What is your age?,What is your gender?,Is there a family history of premature graying?,At what age did you first notice gray hair?,"On a scale of 1 to 10, how would you rate your stress levels?",Do you sleep at least 7 hours a night?,How often do you eat fast food?,Do you smoke or consume alcohol?,How many hours a day do you use your phone?,Do you eat junk food often?,Do you use your phone after 11 PM?
0,2025/04/15 8:57:50 pm GMT+5:30,19.0,Male,no,16.0,8.0,Sometimes,Often,No,More than 6,Yes,Yes
1,2025/04/16 12:30:23 pm GMT+5:30,22.0,Male,yes,18.0,8.0,Yes,Sometimes,No,Less than 2,No,No
2,2025/04/16 12:45:10 pm GMT+5:30,19.0,Male,no,NaN,5.0,Yes,Sometimes,No,4 to 6,Yes,Yes
3,2025/04/16 2:58:02 pm GMT+5:30,NaN,Male,no,NaN,5.0,Yes,Sometimes,No,4 to 6,No,Yes
4,2025/04/16 6:51:39 pm GMT+5:30,16.0,Male,no,15.0,5.0,Yes,Often,No,More than 6,Yes,Yes

In [8]:

df.drop(columns = ['Timestamp', '  What is your gender?  ', '  Do you smoke or consume alcohol?  ','Do you eat junk food often?'],inplace=True)

df.columns

Index(['What is your age? ',
       '  Is there a family history of premature graying?  ',
       '  At what age did you first notice gray hair?  ',
       'On a scale of 1 to 10, how would you rate your stress levels?  ',
       '  Do you sleep at least 7 hours a night?  ',
       '  How often do you eat fast food?  ',
       'How many hours a day do you use your phone?',
       'Do you use your phone after 11 PM?  '],
      dtype='object')

In [9]:
df.columns = ['Age','Family_history','Gray_onset','stress','sleep','fast_food','screen_time','late_phone']

df.head()

,Age,Family_history,Gray_onset,stress,sleep,fast_food,screen_time,late_phone
0,19.0,no,16.0,8.0,Sometimes,Often,More than 6,Yes
1,22.0,yes,18.0,8.0,Yes,Sometimes,Less than 2,No
2,19.0,no,NaN,5.0,Yes,Sometimes,4 to 6,Yes
3,NaN,no,NaN,5.0,Yes,Sometimes,4 to 6,Yes
4,16.0,no,15.0,5.0,Yes,Often,More than 6,Yes

In [10]:

df.isna().sum()

Age               3
Family_history    1
Gray_onset        3
stress            2
sleep             1
fast_food         2
screen_time       2
late_phone        2
dtype: int64

In [12]:
avg_age = df['Age'].median()
print(avg_age)
df['Age'].fillna(value = avg_age,inplace = True)

25.0

C:\Users\Akshay Ghatage\AppData\Local\Temp\ipykernel_22100\1916607513.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(value = avg_age,inplace = True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             21 non-null     float64
 1   Family_history  20 non-null     object
 2   Gray_onset      18 non-null     float64
 3   stress          19 non-null     float64
 4   sleep           20 non-null     object
 5   fast_food       19 non-null     object
 6   screen_time     19 non-null     object
 7   late_phone      19 non-null     object
dtypes: float64(3), object(5)
memory usage: 1.4+ KB

In [19]:
df.isna().sum()

Age               0
Family_history    0
Gray_onset        0
stress            0
sleep             0
fast_food         1
screen_time       1
late_phone        1
dtype: int64

In [16]:

df['Gray_onset']
df.dropna(subset=['Gray_onset'],inplace=True)

In [18]:
mean_stress = df['stress'].mean()
df['stress'].fillna(value = mean_stress,inplace=True)

C:\Users\Akshay Ghatage\AppData\Local\Temp\ipykernel_22100\70047555.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['stress'].fillna(value = mean_stress,inplace=True)

In [20]:
#missing values in fast food
fill_fast_food = df['fast_food'].mode()[0]
df['fast_food'].fillna(value = fill_fast_food,inplace=True)

#missing values in screen time
avg_screen_time = df['screen_time'].mode()[0]
df['screen_time'].fillna(value = avg_screen_time,inplace=True)

#missing values in late phone
avg_late_phone = df['late_phone'].mode()[0]
df['late_phone'].fillna(value = avg_late_phone,inplace = True)

C:\Users\Akshay Ghatage\AppData\Local\Temp\ipykernel_22100\1053959742.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fast_food'].fillna(value = fill_fast_food,inplace=True)
C:\Users\Akshay Ghatage\AppData\Local\Temp\ipykernel_22100\1053959742.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['screen_time'].fillna(value = avg_screen_time,inplace=True)
C:\Users\Akshay Ghatage\AppData\Local\Temp\ipykernel_22100\1053959742.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['late_phone'].fillna(value = avg_late_phone,inplace = True)

In [21]:
df.isna().sum()

Age               0
Family_history    0
Gray_onset        0
stress            0
sleep             0
fast_food         0
screen_time       0
late_phone        0
dtype: int64

In [22]:
print(df.shape)
print(df.isnull().sum())
df.head()

(18, 8)
Age               0
Family_history    0
Gray_onset        0
stress            0
sleep             0
fast_food         0
screen_time       0
late_phone        0
dtype: int64

,Age,Family_history,Gray_onset,stress,sleep,fast_food,screen_time,late_phone
0,19.0,no,16.0,8.0,Sometimes,Often,More than 6,Yes
1,22.0,yes,18.0,8.0,Yes,Sometimes,Less than 2,No
4,16.0,no,15.0,5.0,Yes,Often,More than 6,Yes
5,21.0,no,18.0,5.0,No,Sometimes,2 to 4,No
6,27.0,no,24.0,5.0,Sometimes,Often,More than 6,No

In [23]:
df['Family_history'].value_counts()

Family_history
no     11
yes     7
Name: count, dtype: int64

In [26]:
print(df['Family_history'].unique())
print(df['sleep'].unique())
print(df['late_phone'].unique())
print(df['fast_food'].unique())
print(df['screen_time'].unique())

['no' 'yes']
['Sometimes' 'Yes' 'No']
['Yes' 'No' 'Sometimes']
['Often' 'Sometimes' 'Rarely']
['More than 6' 'Less than 2' '2 to 4' '4 to 6']

In [27]:
df['Family_history'] = df['Family_history'].map({"yes":1,"no":0})
df['sleep'] = df['sleep'].map({"Yes":2,"Sometimes":1,"No":0})
df['late_phone'] = df['late_phone'].map({"Yes":2,"Sometimes":1,"No":0})
df['fast_food'] = df['fast_food'].map({"Often":2,"Sometimes":1,"Rarely":0})
df['screen_time'] = df['screen_time'].map({"More than 6":4,"4 to 6":3, "2 to 4":2,"Less than 2":1})

In [28]:
df.head()

,Age,Family_history,Gray_onset,stress,sleep,fast_food,screen_time,late_phone
0,19.0,0,16.0,8.0,1,2,4,2
1,22.0,1,18.0,8.0,2,1,1,0
4,16.0,0,15.0,5.0,2,2,4,2
5,21.0,0,18.0,5.0,0,1,2,0
6,27.0,0,24.0,5.0,1,2,4,0

In [29]:
print(df.isnull().sum())
print(df.shape)
df.head()

Age               0
Family_history    0
Gray_onset        0
stress            0
sleep             0
fast_food         0
screen_time       0
late_phone        0
dtype: int64
(18, 8)

,Age,Family_history,Gray_onset,stress,sleep,fast_food,screen_time,late_phone
0,19.0,0,16.0,8.0,1,2,4,2
1,22.0,1,18.0,8.0,2,1,1,0
4,16.0,0,15.0,5.0,2,2,4,2
5,21.0,0,18.0,5.0,0,1,2,0
6,27.0,0,24.0,5.0,1,2,4,0

In [31]:
X = df.drop(columns=['Gray_onset'])
Y = df['Gray_onset']

In [32]:
X.head()

    Age  Family_history  stress  sleep  fast_food  screen_time  late_phone
0  19.0               0     8.0      1          2            4           2
1  22.0               1     8.0      2          1            1           0
4  16.0               0     5.0      2          2            4           2
5  21.0               0     5.0      0          1            2           0
6  27.0               0     5.0      1          2            4           0

In [33]:
Y.head()

0    16.0
1    18.0
4    15.0
5    18.0
6    24.0
Name: Gray_onset, dtype: float64

In [36]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)

(14, 7)
(4, 7)

In [38]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,Y_train)

print("Model Trianed")

Model Trianed

In [39]:
Y_pred = model.predict(X_test)

print("Actual Values: ",Y_test.round(2))
print("Predicted Values: " ,Y_pred.round(2))

Actual Values:  0     16.0
1     18.0
10    19.0
7     17.0
Name: Gray_onset, dtype: float64
Predicted Values:  [15.83 19.75 36.72 18.52]

In [40]:
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(Y_test, Y_pred)
r2  = r2_score(Y_test, Y_pred)

print(f"Mean Absolute Error: {mae:.2f} years")
print(f"R2 Score: {r2:.2f}")

Mean Absolute Error: 5.29 years
R2 Score: -62.85

In [42]:
# see what P3's features look like
print(X_test.loc[10])

Age               40.0
Family_history     1.0
stress             4.0
sleep              2.0
fast_food          0.0
screen_time        3.0
late_phone         1.0
Name: 10, dtype: float64

In [46]:
# age=15, family_history=no→0, stress=7, sleep=Sometimes→1, 
# fast_food=Rarely→0, screen_time=4 to 6→3, late_phone=Sometimes→1

girl = pd.DataFrame([[15, 0, 7, 1, 0, 3, 1]], 
                     columns=['Age', 'Family_history', 'stress', 'sleep', 
                               'fast_food', 'screen_time', 'late_phone'])

girl_pred = model.predict(girl)
print(f"Predicted gray onset age: {girl_pred[0]:.2f} years")

Predicted gray onset age: 14.61 years

In [44]:
print(X.columns)

Index(['Age', 'Family_history', 'stress', 'sleep', 'fast_food', 'screen_time',
       'late_phone'],
      dtype='object')

In [45]:
X.head()

    Age  Family_history  stress  sleep  fast_food  screen_time  late_phone
0  19.0               0     8.0      1          2            4           2
1  22.0               1     8.0      2          1            1           0
4  16.0               0     5.0      2          2            4           2
5  21.0               0     5.0      0          1            2           0
6  27.0               0     5.0      1          2            4           0